debug: true
logging:
    level:
        com:
            cplh:
                gis:
                    mapper: debug
spring:
    datasource:
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_cache?useSSL=false&useUnicode=true&characterEncoding=utf8
    redis:
        host: localhost
        password: 123456
    rabbitmq:
        host: order.youpinsanyue.com
        username: rabbit
        password: 'rabbit@123@abc'
mybatis:
    configuration:
        map-underscore-to-camel-case: true # 开启mybatis驼峰命名支持


    