debug: true
server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mbg-dev?serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver