dubbo:
    application:
        name: provider-ticket
    registry:
        address: zookeeper://127.0.0.1:2181
    scan:
        base-packages: com.cplh.gis.ticket.service
#logging:
#    level: debug
debug: true
