dubbo:
    application:
        name: provider-ticket # 指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
    registry:
        address: zookeeper://59.110.174.24:2181
    scan:
        base-packages: com.cplh.gis.ticket.service
    protocol:
        threads: 200
#logging:
#    level: debug
#debug: true
