server:
    port: 8080
spring:
    datasource:
        password: root
        driver-class-name: org.gjt.mm.mysql.Driver
        username: 123
        url: jdbc:mysql://localhost:3306/spring_cache?useSSL=false&useUnicode=true&characterEncoding=utf8



application:
    security:
        browser:
#            login-page: /demo-siginIn.html
            loginType: JSON
        social:
            qq:
                app-id: 1
                app-secret: 1
#        code:
#            image:
#                length: 6
#                width: 100
#                url: /user*