server:
    port: 8080

application:
    security:
        browser:
#            login-page: /demo-siginIn.html
            loginType: JSON
        code:
            image:
                length: 6
                width: 100
                url: /user*