server:
    port: 80
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_cache?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123


# 应用程序相关配置
application:
    security:
        browser:
            signUpUrl: /demo-siginUp.html
#            login-page: /demo-siginIn.html
            loginType: JSON
        social:
            qq:
#                providerId: ""
                app-id: 101748177
                app-secret: da0963e664e7cf496e996a9178e1e827
#            filterProcessesUrl: /callback
#        code:
#            image:
#                length: 6
#                width: 100
#                url: /user*