security:
    oauth2:
        client:
            access-token-uri: http://127.0.0.1:9999/server/oauth/token
            clientId: client1
            clientSecret: secrect1
            user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
        resource:
            jwt:
                key-uri: http://127.0.0.1:9999/server/oauth/token_key

server:
    port: 8080
    servlet:
        context-path: /client1